# Lab 11

In [27]:
import pandas as pd
import numpy as np

__In Class Exercise 1__

In [2]:
permits = pd.read_csv("Film_Permits.csv")

#.shape gives you the total number of rows and columns
permits.shape

#.dytpes gives you the data type of each column
permits.dtypes

#.columns gives you the list of column names
permits.columns

Index(['EventID', 'EventType', 'StartDateTime', 'EndDateTime', 'EnteredOn',
       'EventAgency', 'ParkingHeld', 'Borough', 'CommunityBoard(s)',
       'PolicePrecinct(s)', 'Category', 'SubCategoryName', 'Country',
       'ZipCode(s)'],
      dtype='object')

__In Class Exercise 2__

In [3]:
ending = permits.EndDateTime.loc[0]
event = permits.EventType.loc[1]
category = permits.Category.loc[5]

ending
event
category

'Television'

__In Class Exercise 3__

In [4]:
permits_exercise3 = permits[["StartDateTime", "EndDateTime", "SubCategoryName"]]

permits_exercise3

                StartDateTime             EndDateTime  SubCategoryName
0      03/08/2022 07:00:00 AM  03/08/2022 07:00:00 PM            Pilot
1      03/08/2022 07:00:00 AM  03/08/2022 10:00:00 PM  Episodic series
2      03/08/2022 07:00:00 AM  03/08/2022 09:00:00 PM   Cable-episodic
3      03/08/2022 07:00:00 AM  03/08/2022 08:00:00 PM  Episodic series
4      03/08/2022 04:00:00 PM  03/09/2022 06:00:00 AM          Feature
...                       ...                     ...              ...
12174  09/29/2022 08:00:00 AM  09/29/2022 11:00:00 PM   Cable-episodic
12175  09/29/2022 06:30:00 AM  09/29/2022 06:30:00 PM   Not Applicable
12176  09/29/2022 12:01:00 AM  09/30/2022 11:59:00 PM          Theater
12177  09/29/2022 12:01:00 AM  10/14/2022 06:00:00 AM          Theater
12178  09/29/2022 04:00:00 PM  09/30/2022 03:00:00 AM   Cable-episodic

[12179 rows x 3 columns]

__In Class Exercise 4__

In [5]:
permits_2 = permits.copy()
permits_2.drop(labels = ["EnteredOn", "PolicePrecinct(s)"], axis = 1, inplace = True)

permits_2

,EventID,EventType,StartDateTime,EndDateTime,EventAgency,ParkingHeld,Borough,CommunityBoard(s),Category,SubCategoryName,Country,ZipCode(s)
0,628327,Shooting Permit,03/08/2022 07:00:00 AM,03/08/2022 07:00:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",SUTTON STREET between NORMAN AVENUE and NASSAU...,Brooklyn,1,Television,Pilot,United States of America,11222
1,629351,Shooting Permit,03/08/2022 07:00:00 AM,03/08/2022 10:00:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",COVERT ST between WYCKOFF AVENUE and IRVING AV...,Queens,5,Television,Episodic series,United States of America,"11237, 11385"
2,629319,Shooting Permit,03/08/2022 07:00:00 AM,03/08/2022 09:00:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",WHITE STREET between SEIGEL STREET and MOORE S...,Brooklyn,1,Television,Cable-episodic,United States of America,11206
3,629309,Shooting Permit,03/08/2022 07:00:00 AM,03/08/2022 08:00:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",BARCLAY STREET between BROADWAY and CHURCH STR...,Manhattan,1,Television,Episodic series,United States of America,"10007, 10013, 10282"
4,629504,Shooting Permit,03/08/2022 04:00:00 PM,03/09/2022 06:00:00 AM,"Mayor's Office of Film, Theatre & Broadcasting",WEST 13 STREET between 10 AVENUE and WASHING...,Manhattan,2,Film,Feature,United States of America,10014
...,...,...,...,...,...,...,...,...,...,...,...,...
12174,674627,Shooting Permit,09/29/2022 08:00:00 AM,09/29/2022 11:00:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",REVIEW AVENUE between LAUREL HILL BOULEVARD an...,Queens,"1, 2, 8",Television,Cable-episodic,United States of America,"11101, 11201, 11217, 11222, 11238, 11378"
12175,674638,Shooting Permit,09/29/2022 06:30:00 AM,09/29/2022 06:30:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",Center Dr between EAST DRIVE and 65 st,Manhattan,"5, 64",Still Photography,Not Applicable,United States of America,"10019, 10023"
12176,673442,Theater Load in and Load Outs,09/29/2022 12:01:00 AM,09/30/2022 11:59:00 PM,"Mayor's Office of Film, Theatre & Broadcasting",WEST 55 STREET between 11 AVENUE and 12 AVEN...,Manhattan,4,Theater,Theater,United States of America,10019
12177,672492,Theater Load in and Load Outs,09/29/2022 12:01:00 AM,10/14/2022 06:00:00 AM,"Mayor's Office of Film, Theatre & Broadcasting",LEXINGTON AVENUE between EAST 66 STREET and ...,Manhattan,8,Theater,Theater,United States of America,10065
12178,673981,Shooting Permit,09/29/2022 04:00:00 PM,09/30/2022 03:00:00 AM,"Mayor's Office of Film, Theatre & Broadcasting",METROPOLITAN AVENUE between GRANDVIEW AVE and ...,Queens,5,Television,Cable-episodic,United States of America,"11378, 11385"

__In Class Exercise 5__

In [6]:
eventagency = permits["EventAgency"]
event_dict = {}

for i in eventagency:
    if i not in event_dict:
        event_dict[i] = 1
    else:
        event_dict[i] += 1
        
print(event_dict)

{"Mayor's Office of Film, Theatre & Broadcasting": 12179}

__In Class Exercise 6__

In [7]:
exercise6 = pd.DataFrame(list(event_dict.items()), columns = ["Event Agency", "Amount of Permits"])
                         
exercise6

                                     Event Agency  Amount of Permits
0  Mayor's Office of Film, Theatre & Broadcasting              12179

# Post Lab

_1. use pandas to create a dataframe_

In [8]:
bikeparking = pd.read_csv("BicycleParking.csv")
bikeparking

,the_geom,OBJECTID,BoroCode,BoroName,BoroCD,CounDist,AssemDist,StSenDist,CongDist,REQBBL,...,XSTREET2,SIDE,PROGRAM,ASSETSUBTY,DATE_INST,INTERNALID,NTAName,FEMAFldz,FEMAFldT,HrcEvac
0,POINT (-73.94665719000373 40.71131121432156),1,3,Brooklyn,301,34,53,18,7,3.027870e+09,...,MANHATTAN AV,S,Bike Racks,Small Hoop,07/30/2013 12:00:00 AM,SiteID: S.0016980 (RL.1900.16980/22114),East Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,NaN
1,POINT (-73.88760259761078 40.665945152097834),2,3,Brooklyn,305,42,60,19,8,3.040750e+09,...,SCHENCK ST,NaN,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013260 (RL.1900.13260/12345),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
2,POINT (-73.88760190075236 40.66593971499823),3,3,Brooklyn,305,42,60,19,8,3.040750e+09,...,SCHENCK ST,NaN,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013257 (RL.1900.13257/12346),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
3,POINT (-73.88760119582628 40.665939767439966),4,3,Brooklyn,305,42,60,19,8,3.040750e+09,...,SCHENCK ST,NaN,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013261 (RL.1900.13261/12347),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
4,POINT (-73.88760120507663 40.665934277899765),5,3,Brooklyn,305,42,60,19,8,3.040750e+09,...,SCHENCK ST,NaN,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013258 (RL.1900.13258/12348),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30314,POINT (-73.98873699981141 40.75880799972076),30315,1,Manhattan,104,3,75,47,12,1.010350e+09,...,W 45 Street,W,Bike Corral,Bike Corral,01/05/2023 12:00:00 AM,SiteID: S.0032975 (BC0767),Hell's Kitchen,X,AREA OF MINIMAL FLOOD HAZARD,NaN
30315,POINT (-73.95666899976742 40.717221000422306),30316,3,Brooklyn,301,33,50,59,7,3.023200e+09,...,Bedford Avenue,N,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032970 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30316,POINT (-73.95660500049034 40.717176000336394),30317,3,Brooklyn,301,33,50,59,7,3.023200e+09,...,Bedford Avenue,N,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032971 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30317,POINT (-73.95666899976742 40.717221000422306),30318,3,Brooklyn,301,33,50,59,7,3.023200e+09,...,Bedford Avenue,N,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032969 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30318,POINT (-73.95656399999784 40.717151999786275),30319,3,Brooklyn,301,33,50,59,7,3.023200e+09,...,Bedford Avenue,N,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032972 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0

_2. use three of the techniques we covered in lab to inspect the dataset_

In [9]:
bikeparking.sample(5)
bikeparking.dtypes
bikeparking.NTAName.loc[0]

'East Williamsburg'

_3. give at least two examples of what you could use this dataset for and identify at least two columns that could be deleted_

You could use this dataset to tell which boroughs have the most bike parking and see if you need to add more bike parking for certain boroughs. 

I think you can delete the_geom column because it seems irrelavant for any data anaylsis. You could also delete the side column as there is a lot of NaN values.

_4. make a copy of the dataframe and delete the the two columns you identified above_

In [13]:
bikeparking_copy = bikeparking.copy()
bikeparking_copy.drop(labels = ["the_geom", "SIDE"], axis = 1, inplace = True)

bikeparking_copy

,OBJECTID,BoroCode,BoroName,BoroCD,CounDist,AssemDist,StSenDist,CongDist,REQBBL,IFOADDRESS,...,XSTREET1,XSTREET2,PROGRAM,ASSETSUBTY,DATE_INST,INTERNALID,NTAName,FEMAFldz,FEMAFldT,HrcEvac
0,1,3,Brooklyn,301,34,53,18,7,3.027870e+09,638 GRAND ST,...,LEONARD ST,MANHATTAN AV,Bike Racks,Small Hoop,07/30/2013 12:00:00 AM,SiteID: S.0016980 (RL.1900.16980/22114),East Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,NaN
1,2,3,Brooklyn,305,42,60,19,8,3.040750e+09,639 HENDRIX ST,...,HENDRIX ST,SCHENCK ST,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013260 (RL.1900.13260/12345),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
2,3,3,Brooklyn,305,42,60,19,8,3.040750e+09,639 HENDRIX ST,...,HENDRIX ST,SCHENCK ST,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013257 (RL.1900.13257/12346),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
3,4,3,Brooklyn,305,42,60,19,8,3.040750e+09,639 HENDRIX ST,...,HENDRIX ST,SCHENCK ST,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013261 (RL.1900.13261/12347),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
4,5,3,Brooklyn,305,42,60,19,8,3.040750e+09,639 HENDRIX ST,...,HENDRIX ST,SCHENCK ST,Bike Racks,Large Hoop,09/17/2012 12:00:00 AM,SiteID: S.0013258 (RL.1900.13258/12348),East New York-New Lots,X,AREA OF MINIMAL FLOOD HAZARD,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30314,30315,1,Manhattan,104,3,75,47,12,1.010350e+09,705 8 Avenue,...,W 44 Street,W 45 Street,Bike Corral,Bike Corral,01/05/2023 12:00:00 AM,SiteID: S.0032975 (BC0767),Hell's Kitchen,X,AREA OF MINIMAL FLOOD HAZARD,NaN
30315,30316,3,Brooklyn,301,33,50,59,7,3.023200e+09,552 Driggs Avenue,...,Driggs Avenue,Bedford Avenue,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032970 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30316,30317,3,Brooklyn,301,33,50,59,7,3.023200e+09,552 Driggs Avenue,...,Driggs Avenue,Bedford Avenue,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032971 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30317,30318,3,Brooklyn,301,33,50,59,7,3.023200e+09,552 Driggs Avenue,...,Driggs Avenue,Bedford Avenue,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032969 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0
30318,30319,3,Brooklyn,301,33,50,59,7,3.023200e+09,552 Driggs Avenue,...,Driggs Avenue,Bedford Avenue,Bike Corral,Bike Corral,09/01/2017 12:00:00 AM,SiteID: S.0032972 (BC0768),Williamsburg,X,AREA OF MINIMAL FLOOD HAZARD,5.0

_5. isolate the column "BoroName" and store that in a variable_

In [22]:
borough = bikeparking_copy["BoroName"]
borough

0         Brooklyn
1         Brooklyn
2         Brooklyn
3         Brooklyn
4         Brooklyn
           ...
30314    Manhattan
30315     Brooklyn
30316     Brooklyn
30317     Brooklyn
30318     Brooklyn
Name: BoroName, Length: 30319, dtype: object

_6. using the technique we learned in lab, count the number of available parking spots for bikes in each borough_

In [23]:
borough_dict = {}

for i in borough:
    if i not in borough_dict:
        borough_dict[i] = 1
    else:
        borough_dict[i] += 1
        
print(borough_dict)

{'Brooklyn': 11734, 'Bronx': 3411, 'Manhattan': 8543, 'Queens': 5855, 'Staten Island': 776}

_7. create a dataframe based on that dictionary, make sure to include column names_

In [25]:
dataframe = pd.DataFrame(list(borough_dict.items()), columns = ["Borough", "Parking Spots"])
                         
dataframe

         Borough  Parking Spots
0       Brooklyn          11734
1          Bronx           3411
2      Manhattan           8543
3         Queens           5855
4  Staten Island            776

_8. find the mean amout of bike spots per borough_

In [30]:
dataframe['Parking Spots'].mean()

6063.8

__Work Cited__

https://www.statology.org/mean-of-column-pandas/